module.exports = {
  AccessToken: '../models/access_token.js',
  Appointments: '../models/appointments/appointments.js',
  AppointmentDiagnosisRoleMapping: '../models/appointments/appointment_diagnosis_role_mapping/appointment_diagnosis_role_mapping.js',
  AppointmentExaminationsRoleMapping: '../models/appointments/appointment_examinations_role_mapping/appointment_examinations_role_mapping.js',
  AppointmentInvestigationsRoleMapping: '../models/appointments/appointment_investigations_role_mapping/appointment_investigations_role_mapping.js',
  AppointmentLogs: '../models/appointments/appointment_logs/appointment_logs.js',
  AppointmentSymptomsRoleMapping: '../models/appointments/appointment_symptoms_role_mapping/appointment_symptoms_role_mapping.js',
  Diagnosis: '../models/diagnosis/diagnosis.js',
  DiagnosisRoleMapping: '../models/diagnosis/diagnosis_role_mapping/diagnosis_role_mapping.js',
  Examinations: '../models/examinations/examinations.js',
  ExaminationsRoleMapping: '../models/examinations/examinations_role_mapping/examinations_role_mapping.js',
  Investigations: '../models/investigations/investigations.js',
  InvestigationsRoleMapping: '../models/investigations/investigations_role_mapping/investigations_role_mapping.js',
  Medicines: '../models/medicines.js',
  PatientPrescription: '../models/patients/patients_prescription/patient_prescription.js',
  Patients: '../models/patients/patients.js',
  Roles: '../models/roles/roles.js',
  Symptoms: '../models/symptoms/symptoms.js',
  SymptomsRoleMapping: '../models/symptoms/symptoms_role_mapping/symptoms_role_mapping.js'
}